version: '3.8'

services:
  # Servicio de Base de Datos
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: banco_db
      POSTGRES_USER: user_banco
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      # IMPORTANTE: Mapea tu script SQL a esta carpeta específica
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_banco -d banco_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servicio del Backend
  api:
    build: .
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy # Espera a que el Healthcheck de la DB pase
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/banco_db
      SPRING_DATASOURCE_USERNAME: user_banco
      SPRING_DATASOURCE_PASSWORD: password123
      # Usamos 'validate' porque el script SQL ya crea las tablas
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  postgres_data: